# action.yml
name: 'Register Docker artifact in EOF Deploy'
description: 'Notify EOF Deploy about recent pushed docker containers.'
inputs:
  docker-image:
    description: 'Docker image incl. tag that have been pushed to the registry.'
    required: true
  org-id:
    description: 'EOF OrgId.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --docker-image=${{ inputs.docker-image }}
    - --org-id=${{ inputs.org-id }}